pths_dir: /home/lzc/WSIS-Benchmark/pths

voc:
#    train_json_file: /home/lzc/WSIS-Benchmark/dataset/VOCdevkit/VOC2012/annotations/voc_2012_trainaug.json
    train_json_file: /home/data2/Dataset/VOC2012/VOC2012_old/annotations/voc_2012_trainaug.json
    val_json_file: /home/data2/Dataset/VOC2012/VOC2012_old/annotations/voc_2012_val.json
    img_dir_train: /home/data2/Dataset/VOC2012/VOC2012_old/JPEGImages
    img_dir_val: /home/data2/Dataset/VOC2012/VOC2012_old/JPEGImages
    train_proposals: /home/data2/Dataset/VOC2012/VOC2012_old/COB_SBD_trainaug
    val_proposals: /home/data2/Dataset/VOC2012/VOC2012_old/output
    train_cob_proposal_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/voc_2012_cobtrainaug_num200_resolution7.pkl  # 将proposal记录为7*7的大小
    val_cob_proposal_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/voc_2012_sbdval_num200_resolution7.pkl

    train_cob_proposal_file_roialign: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/voc_2012_cobtrainaug_num200_resolution7_roialign.pkl
    val_cob_proposal_file_roialign: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/voc_2012_sbdval_num200_resolution7_roialign.pkl

    prm_path: /home/lzc/WSIS-Benchmark/pths/WSRCNN/prm_ref.pth # PRM 原作者的pth
    train_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_prmref_assign.pkl # 伪标签位置
    aff_prm_path: /home/lzc/WSIS-Benchmark/pths/WSRCNN/FPN_PRM.pth # 将 原作者的 pth 的模型进行重新命名以后的pth
    train_RW_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_prmref_RW_assign.pkl # 使用了 RW 的伪标签位置
    train_smooth_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_prmref_smooth_assign.pkl # 使用了 RW 的伪标签位置
    train_PAM_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_PAM_assign.pkl
    train_best_peak_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_best_peak_assign.pkl
    train_topk_peak_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_top{}_peak_assign.pkl
    train_topk_peak_EM_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_top{}_peak_assign_EM.pkl
    train_cls_iou_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_cls_iou_assign.pkl

    # super pixel model
    train_super_pixels_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/sp_voc_dir/train_super_pixel_proposal.pkl
    val_super_pixels_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/sp_voc_dir/val_super_pixel_proposal.pkl

    sp_label_dir: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/sp_voc_dir/voc_sp_label # 文件夹中有一个一个的 pkl文件, sp_label
    super_pixel_adj_dir: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/sp_voc_dir/voc_super_pixel_adj # 文件夹中有一个一个的 pkl文件 --> (2, edge_num)
    train_sp_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/voc_2012_sp_assign.pkl # 伪标签位置

    train_proposal_score_dir: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob_score/voc_2012_trainaug

coco:
    train_json_file: /home/lzc/WSIS-Benchmark/dataset/coco2017/annotations/instances_train2017.json
    val_json_file: /home/lzc/WSIS-Benchmark/dataset/coco2017/annotations/instances_val2017.json
    test_json_file: /home/lzc/WSIS-Benchmark/dataset/coco2017/annotations/image_info_test-dev2017.json
    img_dir_train: /home/lzc/WSIS-Benchmark/dataset/coco2017/train2017
    img_dir_val: /home/lzc/WSIS-Benchmark/dataset/coco2017/val2017
    img_dir_test: /home/lzc/WSIS-Benchmark/dataset/coco2017/test2017
    train_proposals: /home/lzc/WSIS-Benchmark/dataset/coco2017/COB-COCO
    val_proposals: /home/lzc/WSIS-Benchmark/dataset/coco2017/COB-COCO
    test_proposals: /home/lzc/WSIS-Benchmark/dataset/coco2017/COB-COCO
    train_cob_proposal_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/coco_2017_train.pkl  # 将proposal记录为7*7的大小
    val_cob_proposal_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/coco_2017_val.pkl
    test_cob_proposal_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/cob/coco_2017_test.pkl
    prm_path: /home/lzc/WSIS-Benchmark/pths/WSRCNN/prm_coco.pth
    train_assign_file: /home/lzc/WSIS-Benchmark/code/WSRCNN-troch1.6/data/label_assign/coco_2017_assign.pkl # 伪标签位置
