MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: resnet50.torch_resnet50
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: True

NUM_GPUS: 2
REFINE_TIMES: 3
DEDUP_BOXES: 0.0
transform_mode: ToTensor
step_rate: 0.1
easy_case_mining: True

iou_dir: "./data/cob_iou/VOC2012"
asy_iou_dir: "./data/cob_asy_iou/VOC2012"

ResNet:
  FREEZE_AT: 2

SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0005
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000]
FAST_RCNN:
  ROI_BOX_HEAD: resnet50.roi_2mlp_head_refine_model_mask_fuse
  ROI_XFORM_METHOD: RoIAlign # RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  MLP_HEAD_DIM: 4096
  MASK_SIZE: 7
TRAIN:
#  SCALES: (480, )
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 4096
  PROPOSAL_FILES: ('./data/cob/voc_2012_trainaug.pkl',) # edit
  REFINE_FILES: ("./data/label_assign/voc_2012_label_assign.pkl",)
TEST:
  SCORE_THRESH: 1e-5
  PROPOSAL_FILTER: False
  SCALE: 480
  MAX_SIZE: 2000
  NMS: 0.3
  PROPOSAL_FILES: ('./data/cob/voc_2012_val.pkl',)
  BBOX_AUG:
    ENABLED: True
    H_FLIP: True
    SCALES: (576, 688, 864, 1200)
    SCALE_H_FLIP: True
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'ID'
